### ISSUE TITLE
Improper removal of talents

### ISSUE THREAD

**Issue by Epicurtious** [hawaiisa/vanillaplus-talent-calculator#3]
I was playing around with the calculator and found that there are some configurations that allow one to remove talents they should not be be able to and vise versa
Take for example this tree: https://hawaiisa.github.io/vanillaplus-talent-calculator/#/rogue/IXCA00D-I-K32J1EJJ
You are able to remove talents in the assassination tree without removing the Cold Blood talent even if removing those talents should make Cold Blood inaccessible.
Additionally: https://hawaiisa.github.io/vanillaplus-talent-calculator/#/rogue/0-0-KX20I
You are unable to remove talents in the top row of the Subtlety even though there is already 5 points there and it should interfere with the 3 in Improved Ambush.
This behavior is only seen when all of the talents are taken in the first row, it is not seen when you have not completed all the talents (https://hawaiisa.github.io/vanillaplus-talent-calculator/#/rogue/0-0-EX20I)

**Comment by hawaiisa** [comment]
Hey.

I've noticed this issue, and I believe it's present in the upbranch repo as well. To be honest I'm not really sure what's causing it, and my knowledge of React is very limited (All I've done is pretty much replacing the strings and values of the original talents so they represent the V+ trees. Someday I might get the extra time to try and understand the underlying issue, but for the moment my best suggestion for a fix will be to make sure the talent trees are actually possible ingame while theorycrafting.

Higher on my list of priorities is to make the tooltips stay on-screen (And not overflow out of the screen) on mobile devices, as well as support for locales. Again, React (And web development in general) is something I want to dive more into, but for the time being I'm not really sure what I'm doing.

Thanks for pointing it out, though! It's on my list of things to look into, though I've no timeline on when (or if) any of these things will happen.
