### ISSUE TITLE
(Paladin)

### ISSUE THREAD

**Issue by tiffanyplus** [hawaiisa/vanillaplus-talent-calculator#4]
- Conviction
It should display "Increases your chance to get a critical strike with attacks and offensive spells by x%"

- Seal of command
It should be 50% instead of 70%

- Crusader Strike
It should be 15 sec instead of 30 and stacking up to 5 instead of 7

- One-Handed weapon spec
It should be 3% instead of 2%

- Vindication
Forgot a % on the 10 stat

i think that was all

**Comment by hawaiisa** [comment]
Hey, thanks for pointing it out. Finally got around to updating it! Let me know if you stumble upon more errors.

Cheers!
